### PR TITLE
Use quarkus-hazelcast-client extension

### PR DESCRIPTION
**Pull request by pivovarit**

### CODE REVIEW

**Review by leszko — APPROVED** [review]

**Review by hasancelik — CHANGES_REQUESTED** [review]
@pivovarit jenkins job failed due to below errors from client side(similar to https://github.com/hazelcast/hazelcast-kubernetes/issues/181):
```
Caused by: com.hazelcast.config.InvalidConfigurationException: Invalid configuration
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:147)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:57)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
	at com.hazelcast.client.impl.clientside.ClusterDiscoveryServiceBuilder.initDiscoveryService(ClusterDiscoveryServiceBuilder.java:246)
	at com.hazelcast.client.impl.clientside.ClusterDiscoveryServiceBuilder.build(ClusterDiscoveryServiceBuilder.java:99)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.initClusterDiscoveryService(HazelcastClientInstanceImpl.java:285)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:242)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:458)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at HazelcastClientConfig.createInstance(HazelcastClientConfig.java:19)
	at HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.create(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:236)
	at HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.create(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:96)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.get(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:140)
	at HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.get(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:38)
	at CommandController_Bean.create(CommandController_Bean.zig:64)
	... 37 more
Caused by: com.hazelcast.config.properties.ValidationException: There is no discovery strategy factory to create 'DiscoveryStrategyConfig{properties={service-name=hazelcast-cluster}, className='com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy', discoveryStrategyFactory=null}' Is it a typo in a strategy classname? Perhaps you forgot to include implementation on a classpath?
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:186)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141)
	... 57 more
```
[full.log](https://github.com/hazelcast-guides/hazelcast-quarkus/files/4449404/full.log)
test suite --> https://github.com/hasancelik/hazelcast-qe/tree/use-stable-version/it/kubernetes/quarkus-extension
jenkins job --> http://jenkins.hazelcast.com/view/Integration%20Tests/job/kubernetes-quarkus-client-extension/56/
used versions --> http://jenkins.hazelcast.com/view/Integration%20Tests/job/kubernetes-quarkus-client-extension/56/parameters/

**Comment by pivovarit** [comment]
@hasancelik When you did the testing, it worked with _master_ branch, right?

**Comment by hasancelik** [comment]
> @hasancelik When you did the testing, it worked with _master_ branch, right?

I just saw your PR and decided to test new release(1.0.0-RC2) with existing job after some modifications(As you know, previous version of it was building quarkus jars from your fork(999-SNAPSHOT) then start to tests). 

Actually, jenkins job does not running directly on master branch of this guide. It uses different configuration from master branch. For example as you can see at error logs, client application at test suite uses k8s discovery(like [quarkus-kubernetes guide](https://github.com/hazelcast-guides/hazelcast-quarkus-kubernetes))
https://github.com/hasancelik/hazelcast-qe/blob/use-stable-version/it/kubernetes/quarkus-extension/quarkus-client-app/src/main/java/HazelcastClientConfig.java

**Comment by hasancelik** [comment]
I have created new issue at `quarkus-hazelcast-client` repo related to above errors:
https://github.com/hazelcast/quarkus-hazelcast-client/issues/18

**Review by hasancelik — APPROVED** [review]

**Review by mesutcelik — APPROVED** [review]

**Pull request merged**
